# HandReceipt Backend Configuration

# Server configuration
server:
  port: 8000
  host: "localhost"
  environment: "development" # "development", "production"

# Database configuration
database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  user: "brendantoole"
  password: "Dunlainge1!" # Note: For production, use environment variables instead
  name: "handreceipt_db"
  ssl_mode: "disable"

# AWS QLDB configuration
qldb:
  ledger_name: "handreceipt-ledger"
  region: "us-east-1"
  # Tables to create if they don't exist
  tables:
    - "ItemCreations"
    - "TransferEvents"
    - "StatusChanges"
    - "VerificationEvents"
    - "CorrectionEvents"

# Auth configuration
auth:
  jwt_secret: "" # Don't store actual secrets in config files, use environment variables
  access_token_expiry: 24h # 24 hours
  refresh_token_expiry: 168h # 7 days
  session_expiry: 24h # 24 hours
  session_secret: "temporary-session-secret" # Replace with environment variable in production 